/**
 *
 */
package main.cz.hlubyluk.adventofcode.event2019;

import main.cz.hlubyluk.adventofcode.IDay;

/**
 * @author hlubyluk
 *
 */
public interface IE19D06 extends IDay {
  String TEST_INPUT = "COM)B\n" + "B)C\n" + "C)D\n" + "D)E\n" + "E)F\n" + "B)G\n" + "G)H\n" + "D)I\n" + "E)J\n"
      + "J)K\n" + "K)L";

  String INPUT = "3ZP)TWL\n" +
      "Q6Y)XTN\n" +
      "CH8)KBM\n" +
      "LM9)J36\n" +
      "JR3)H4Y\n" +
      "K78)N2S\n" +
      "64C)8RP\n" +
      "9SN)LSL\n" +
      "FP6)68K\n" +
      "22G)6PB\n" +
      "45K)2GQ\n" +
      "66X)GNJ\n" +
      "YX4)GZV\n" +
      "PZV)VWL\n" +
      "ZMF)VK9\n" +
      "NJL)TB7\n" +
      "CDK)TY7\n" +
      "Q5G)4XG\n" +
      "4X1)NQQ\n" +
      "MPH)2R1\n" +
      "S89)KGM\n" +
      "3GL)9K2\n" +
      "1LQ)K8W\n" +
      "YCY)WW4\n" +
      "S4L)615\n" +
      "X4H)Q89\n" +
      "97J)V45\n" +
      "1SX)KSQ\n" +
      "1WP)7GW\n" +
      "DD2)2YF\n" +
      "NFK)1QL\n" +
      "R9X)JR1\n" +
      "PY2)B3J\n" +
      "9JP)VHF\n" +
      "PP6)CDK\n" +
      "4V3)7CX\n" +
      "JB2)K18\n" +
      "M55)ZF3\n" +
      "MNM)TMN\n" +
      "984)2KC\n" +
      "N9C)JY4\n" +
      "Z96)QDP\n" +
      "78K)9WY\n" +
      "CR3)KDC\n" +
      "483)Q4R\n" +
      "N1L)W65\n" +
      "698)C7T\n" +
      "ZX7)3F8\n" +
      "QBJ)82J\n" +
      "CNF)DH1\n" +
      "V6S)H4B\n" +
      "CRW)FC5\n" +
      "F4Y)9WC\n" +
      "Z6H)DK4\n" +
      "J82)R1H\n" +
      "8XG)3WM\n" +
      "8QZ)F55\n" +
      "82C)VGJ\n" +
      "ZSR)KZD\n" +
      "1SN)MPC\n" +
      "MM2)SCZ\n" +
      "N5V)SCV\n" +
      "XPB)LSV\n" +
      "WDM)KNZ\n" +
      "S53)7MW\n" +
      "YRK)C4V\n" +
      "DY9)YLQ\n" +
      "G9X)JYF\n" +
      "FT1)318\n" +
      "G5F)VVX\n" +
      "CKN)J7J\n" +
      "1T7)LP6\n" +
      "K1H)8MF\n" +
      "213)DRD\n" +
      "752)LVP\n" +
      "FP1)RZX\n" +
      "DV7)3Z5\n" +
      "PM9)LWF\n" +
      "Q1Q)2ZM\n" +
      "8KT)B4M\n" +
      "QGH)RNP\n" +
      "VGV)LKK\n" +
      "TXJ)239\n" +
      "52D)YRK\n" +
      "QK9)GFB\n" +
      "BB9)QDJ\n" +
      "46M)MQR\n" +
      "RLC)FCJ\n" +
      "TW6)3G1\n" +
      "XQD)9BQ\n" +
      "R4G)QW2\n" +
      "LD8)JP8\n" +
      "VQZ)Q45\n" +
      "TZD)RRV\n" +
      "RRV)SHJ\n" +
      "YL4)3GR\n" +
      "K2W)K1P\n" +
      "X6M)CCC\n" +
      "M3Q)TK5\n" +
      "X4M)MMV\n" +
      "9KR)DS5\n" +
      "6V7)7TH\n" +
      "8K8)W6C\n" +
      "JZR)Q28\n" +
      "B1B)3Y2\n" +
      "MD1)SYX\n" +
      "1NM)1D2\n" +
      "ML7)Z59\n" +
      "89S)CVG\n" +
      "DXM)JMF\n" +
      "ZKG)YXG\n" +
      "LSL)88Y\n" +
      "RNS)B7C\n" +
      "KSR)2HG\n" +
      "8TQ)G4H\n" +
      "JTD)S4K\n" +
      "VY9)RBC\n" +
      "TD4)FQJ\n" +
      "L8R)PY9\n" +
      "H4B)2FT\n" +
      "WQF)CYJ\n" +
      "FQJ)3CJ\n" +
      "YRK)GXG\n" +
      "G62)2Q8\n" +
      "DTZ)T5B\n" +
      "JZ6)47G\n" +
      "1R7)DMZ\n" +
      "DMX)386\n" +
      "PX2)TVJ\n" +
      "BJR)942\n" +
      "D7D)GNR\n" +
      "7HY)LXC\n" +
      "MNK)8GH\n" +
      "KT2)WTH\n" +
      "WH8)LSR\n" +
      "1F4)N5V\n" +
      "GD9)WKV\n" +
      "Z5W)MWK\n" +
      "VVX)YG1\n" +
      "8DD)SSX\n" +
      "V9K)YM1\n" +
      "3LZ)BP7\n" +
      "5Q5)D5G\n" +
      "RSR)4CH\n" +
      "2HG)9ZD\n" +
      "6MV)84C\n" +
      "X1R)WM3\n" +
      "3QH)92H\n" +
      "1SG)2CN\n" +
      "X2G)QMG\n" +
      "8YH)HX9\n" +
      "WL1)5FF\n" +
      "6CS)52D\n" +
      "8VH)1HR\n" +
      "JP8)ZQL\n" +
      "CQP)WZC\n" +
      "RQ5)SWQ\n" +
      "G62)ZB4\n" +
      "2KY)TN1\n" +
      "5T5)22G\n" +
      "823)5LS\n" +
      "6B2)D5B\n" +
      "KQM)78K\n" +
      "ZQL)5K7\n" +
      "BZH)CY8\n" +
      "S6H)3RS\n" +
      "TL3)PZV\n" +
      "3N2)53S\n" +
      "CHW)1G8\n" +
      "SHJ)SG9\n" +
      "P3F)YRW\n" +
      "QDQ)XH5\n" +
      "JSQ)31X\n" +
      "J8Q)BY9\n" +
      "68G)V2V\n" +
      "W9D)P5V\n" +
      "X1R)VJG\n" +
      "4CD)85F\n" +
      "17X)PJ1\n" +
      "66M)K3B\n" +
      "R66)2JS\n" +
      "B6P)721\n" +
      "YHQ)4L3\n" +
      "NTT)CM8\n" +
      "2ZQ)CT7\n" +
      "6WW)L3S\n" +
      "B6F)53P\n" +
      "KLW)749\n" +
      "86C)Z4L\n" +
      "TSV)GTB\n" +
      "K4B)RV1\n" +
      "VR4)BGL\n" +
      "Y7Y)BFQ\n" +
      "DZL)WQH\n" +
      "H1X)1MP\n" +
      "Z6H)VYZ\n" +
      "BNR)NH9\n" +
      "BQ5)JN1\n" +
      "NHT)MNW\n" +
      "XPM)NW3\n" +
      "XYN)96S\n" +
      "BH9)NCD\n" +
      "QM7)6P9\n" +
      "4B7)Y5T\n" +
      "GJD)9F2\n" +
      "P5V)CQZ\n" +
      "QZ5)7Q1\n" +
      "SBB)S2N\n" +
      "NRT)9TZ\n" +
      "3Z1)QRP\n" +
      "T88)BF3\n" +
      "9JS)2WN\n" +
      "FJ3)B4H\n" +
      "NVN)GLT\n" +
      "P1V)ZSR\n" +
      "245)9KS\n" +
      "F1G)FDR\n" +
      "TFB)W3X\n" +
      "3Q1)733\n" +
      "QRP)7RJ\n" +
      "6KT)9PV\n" +
      "JMN)WH8\n" +
      "ZP8)TQC\n" +
      "P28)9SN\n" +
      "68C)3N2\n" +
      "R77)JZP\n" +
      "YQQ)Z49\n" +
      "F1G)LPX\n" +
      "PMJ)8FP\n" +
      "CYX)WP8\n" +
      "D82)ZWH\n" +
      "BZS)F25\n" +
      "B19)DBY\n" +
      "2L4)TTR\n" +
      "FPR)LJC\n" +
      "GZV)MYJ\n" +
      "863)H9D\n" +
      "TB7)TGW\n" +
      "FQX)P5M\n" +
      "DXC)TNQ\n" +
      "RL6)9MJ\n" +
      "Q45)814\n" +
      "P8C)1WJ\n" +
      "4XG)MTL\n" +
      "B7C)7F4\n" +
      "KFZ)9KX\n" +
      "GQ3)MYG\n" +
      "CL1)Y7Y\n" +
      "VTS)5Q5\n" +
      "F7V)9RH\n" +
      "HJ3)R77\n" +
      "L95)RBD\n" +
      "BS7)HR9\n" +
      "MXP)NGP\n" +
      "1D4)6JF\n" +
      "PSV)YGZ\n" +
      "PYF)VHG\n" +
      "3NN)1YT\n" +
      "C4G)9V4\n" +
      "HSP)NRZ\n" +
      "Y15)ZN5\n" +
      "2VX)9LH\n" +
      "ND1)79L\n" +
      "RGY)6XH\n" +
      "WRX)F58\n" +
      "LGL)P9F\n" +
      "CBB)DY3\n" +
      "65K)92P\n" +
      "HNF)J6Y\n" +
      "1T8)8DD\n" +
      "F2F)W4T\n" +
      "RG1)HRF\n" +
      "8CH)765\n" +
      "SYX)97L\n" +
      "5M8)ZQ1\n" +
      "W3Y)24V\n" +
      "GNR)GZW\n" +
      "VRX)J7V\n" +
      "M7D)JZR\n" +
      "1HR)JBC\n" +
      "T95)PS7\n" +
      "WVZ)TC7\n" +
      "P57)P95\n" +
      "G6Q)CLF\n" +
      "K9V)CL1\n" +
      "14M)DPN\n" +
      "XF3)ZP5\n" +
      "6LS)P57\n" +
      "VL2)6VB\n" +
      "C51)5NZ\n" +
      "MSQ)ZSP\n" +
      "J6X)SQP\n" +
      "7MW)PHD\n" +
      "LY8)FZG\n" +
      "MW1)B97\n" +
      "Y2P)C4C\n" +
      "386)6L6\n" +
      "LQH)R15\n" +
      "NN6)X4M\n" +
      "9VW)KP5\n" +
      "QYT)GSJ\n" +
      "437)N7L\n" +
      "N3G)NV9\n" +
      "YV3)YBG\n" +
      "LCX)C64\n" +
      "T75)98Z\n" +
      "9S7)666\n" +
      "VVX)984\n" +
      "HGD)YL4\n" +
      "3LH)H8K\n" +
      "VYZ)K78\n" +
      "FZL)D45\n" +
      "V3R)YKL\n" +
      "PSS)FZ5\n" +
      "97L)GWT\n" +
      "59T)5RL\n" +
      "PNV)VK2\n" +
      "7RM)2Z2\n" +
      "46R)ZJ2\n" +
      "R7D)1DG\n" +
      "V77)KRP\n" +
      "XRC)8BK\n" +
      "YKT)V6P\n" +
      "8GN)QLQ\n" +
      "79L)4H6\n" +
      "2WF)HR2\n" +
      "R2M)2VR\n" +
      "7LD)M3K\n" +
      "2PZ)4FF\n" +
      "4VS)JRR\n" +
      "2HG)86F\n" +
      "FNY)NHT\n" +
      "PK6)W1T\n" +
      "YGR)BXQ\n" +
      "8XB)L7F\n" +
      "XV9)B7M\n" +
      "5NZ)6BJ\n" +
      "9N4)NB1\n" +
      "8LK)KL8\n" +
      "9NZ)8PS\n" +
      "XSC)JV9\n" +
      "527)ZQZ\n" +
      "129)WWX\n" +
      "YFF)RLQ\n" +
      "JYF)X9T\n" +
      "RM9)B2N\n" +
      "3Y2)TZ1\n" +
      "Q17)JMC\n" +
      "HBB)W4G\n" +
      "BSB)TY3\n" +
      "2C7)G91\n" +
      "CGY)ZM1\n" +
      "817)KF5\n" +
      "R96)XHF\n" +
      "J9T)FP1\n" +
      "HB3)ZN4\n" +
      "XXP)DDR\n" +
      "QVG)BVM\n" +
      "PXC)PJG\n" +
      "ZNQ)KR6\n" +
      "78Q)2N5\n" +
      "WFJ)NJN\n" +
      "B3G)9BX\n" +
      "QFQ)HTL\n" +
      "VK8)PX2\n" +
      "4KT)HP2\n" +
      "FK6)3HB\n" +
      "9MJ)QYN\n" +
      "XNG)KR4\n" +
      "N1W)YV9\n" +
      "2Q8)B98\n" +
      "SSP)GSB\n" +
      "V3L)1W6\n" +
      "RT6)HDZ\n" +
      "TWL)PP6\n" +
      "266)RCH\n" +
      "5Y7)C9W\n" +
      "83W)W28\n" +
      "784)FQT\n" +
      "JZP)744\n" +
      "N7L)GJK\n" +
      "VS6)VLN\n" +
      "QR5)X9Y\n" +
      "G91)5KX\n" +
      "Q3Y)6FG\n" +
      "RZX)P29\n" +
      "ZJ2)9ZH\n" +
      "FNS)TR9\n" +
      "G6Y)1SG\n" +
      "MJP)T18\n" +
      "L9G)79J\n" +
      "92P)WFJ\n" +
      "SG9)XGN\n" +
      "LJJ)RN2\n" +
      "BGL)429\n" +
      "4H1)M4H\n" +
      "3ZX)9NZ\n" +
      "M3K)6FF\n" +
      "DBL)YHQ\n" +
      "96B)66X\n" +
      "18Q)3PZ\n" +
      "95Z)9S7\n" +
      "ZPY)C8V\n" +
      "RC8)JRY\n" +
      "M4H)FJS\n" +
      "GDZ)XMJ\n" +
      "262)MTG\n" +
      "45K)CHP\n" +
      "V2V)QVG\n" +
      "5CY)BXS\n" +
      "NPC)Y52\n" +
      "FLR)DYG\n" +
      "B5N)W5F\n" +
      "4N2)79X\n" +
      "RXQ)2RH\n" +
      "RNV)435\n" +
      "X4Z)XFR\n" +
      "5K7)65K\n" +
      "666)4KC\n" +
      "459)F4K\n" +
      "B1B)XWW\n" +
      "RNQ)KPS\n" +
      "YQM)MQY\n" +
      "HQM)R94\n" +
      "4B4)SG3\n" +
      "LVP)GQ6\n" +
      "WPQ)1MG\n" +
      "2WN)FVY\n" +
      "H89)3GL\n" +
      "9BT)8LV\n" +
      "XS8)P41\n" +
      "V71)25S\n" +
      "BN6)WVZ\n" +
      "GM7)GZB\n" +
      "1DQ)LBK\n" +
      "R7S)816\n" +
      "12C)M55\n" +
      "SYS)HZJ\n" +
      "88D)NRT\n" +
      "DPN)K6H\n" +
      "GZW)B3Z\n" +
      "JNB)815\n" +
      "WVH)2Q7\n" +
      "XGV)PLJ\n" +
      "12G)SHZ\n" +
      "JXT)DD2\n" +
      "COM)RT6\n" +
      "B7L)MSQ\n" +
      "632)262\n" +
      "9CN)FVL\n" +
      "HLJ)GVN\n" +
      "3MR)DSN\n" +
      "DTY)QBH\n" +
      "MWN)Z77\n" +
      "CQB)BW7\n" +
      "6DV)Z27\n" +
      "VLM)LG9\n" +
      "YQD)H18\n" +
      "PBB)85V\n" +
      "CSR)729\n" +
      "CRP)8SN\n" +
      "GDF)R9X\n" +
      "S49)W48\n" +
      "YNV)896\n" +
      "PNS)T2T\n" +
      "G7J)2CP\n" +
      "PVH)XS8\n" +
      "F9T)1G2\n" +
      "WR3)ZQ5\n" +
      "KD6)Q76\n" +
      "M54)7WQ\n" +
      "HN6)7C8\n" +
      "KHZ)899\n" +
      "WW5)B61\n" +
      "V3M)D7D\n" +
      "956)4NF\n" +
      "8M2)J3N\n" +
      "KN7)2RY\n" +
      "YSM)T65\n" +
      "ZWN)J25\n" +
      "53P)B3T\n" +
      "SJD)JPB\n" +
      "GSJ)98C\n" +
      "ZD5)VGL\n" +
      "L4K)5WQ\n" +
      "85Q)2Q3\n" +
      "3TK)ZMG\n" +
      "JL2)3DJ\n" +
      "BYM)QDQ\n" +
      "6NG)B19\n" +
      "YG1)8Q9\n" +
      "T5B)YCG\n" +
      "4LK)8DS\n" +
      "S8T)76W\n" +
      "WTH)Q8Z\n" +
      "8SN)7Q4\n" +
      "B7B)BSB\n" +
      "6YZ)CRP\n" +
      "VTS)XFN\n" +
      "B4P)3NZ\n" +
      "6L6)JV5\n" +
      "WDZ)1XL\n" +
      "NX3)RLZ\n" +
      "H9L)5FD\n" +
      "995)FD7\n" +
      "M7G)SSP\n" +
      "TY7)ZVG\n" +
      "3DJ)Q56\n" +
      "RRV)5FL\n" +
      "BD8)FNY\n" +
      "VJX)Y5G\n" +
      "N5V)RCW\n" +
      "MPC)F9C\n" +
      "CQZ)YFF\n" +
      "HDZ)HQM\n" +
      "H56)KDP\n" +
      "J2X)KMT\n" +
      "7GW)MK7\n" +
      "43L)M3Q\n" +
      "QDX)PZN\n" +
      "814)44F\n" +
      "CX9)4X1\n" +
      "PY9)DV7\n" +
      "P5K)FVN\n" +
      "VHK)8TQ\n" +
      "KPS)Z47\n" +
      "FGN)DQV\n" +
      "G3T)61M\n" +
      "R4G)HB3\n" +
      "WDD)G9P\n" +
      "H1V)M5B\n" +
      "TBY)G4B\n" +
      "SFR)VJX\n" +
      "24X)WQN\n" +
      "Y61)ZC5\n" +
      "94C)ZD4\n" +
      "FXR)26S\n" +
      "1W6)R88\n" +
      "NCY)RPZ\n" +
      "3G7)YR3\n" +
      "7KL)W2Q\n" +
      "J5G)989\n" +
      "JMC)WBJ\n" +
      "BBB)C95\n" +
      "1VV)9PX\n" +
      "1WS)96B\n" +
      "GMM)N1K\n" +
      "FFL)N7V\n" +
      "PHD)SPZ\n" +
      "WCL)PS2\n" +
      "5J7)64M\n" +
      "8Q7)8YB\n" +
      "NRK)J4L\n" +
      "WLV)538\n" +
      "59X)TSV\n" +
      "CQR)4XR\n" +
      "P33)93T\n" +
      "BPR)F73\n" +
      "3RS)X83\n" +
      "P51)8VS\n" +
      "Q28)6JB\n" +
      "615)NNK\n" +
      "643)VT2\n" +
      "RN2)CZ2\n" +
      "HJW)4C1\n" +
      "PJ3)9FT\n" +
      "M78)XFC\n" +
      "VCT)BYM\n" +
      "C8Z)2NX\n" +
      "4GF)9BC\n" +
      "H8K)M9F\n" +
      "P9F)2C7\n" +
      "NNZ)F8R\n" +
      "6CL)SJD\n" +
      "GXG)2KY\n" +
      "55N)G3X\n" +
      "2TX)R48\n" +
      "4RG)QK1\n" +
      "YSQ)TD4\n" +
      "JVW)87V\n" +
      "5FD)NP7\n" +
      "LVM)K5L\n" +
      "2M7)1NM\n" +
      "JHN)JNB\n" +
      "NQQ)V5J\n" +
      "HX9)ZZD\n" +
      "5FF)C5Y\n" +
      "V45)59F\n" +
      "MMF)SLV\n" +
      "Y7R)2ML\n" +
      "ZZD)HXW\n" +
      "Z69)BP8\n" +
      "XKP)QN8\n" +
      "YGK)RNQ\n" +
      "F6X)QJY\n" +
      "FPV)ZK9\n" +
      "XWX)YV3\n" +
      "RPZ)NX6\n" +
      "49Z)L23\n" +
      "99L)643\n" +
      "TP1)YW5\n" +
      "BW7)9XJ\n" +
      "2ZQ)4H1\n" +
      "N7V)1TD\n" +
      "PZN)KCM\n" +
      "CHL)M78\n" +
      "MCS)CYW\n" +
      "JXW)VH2\n" +
      "ZQZ)CRW\n" +
      "KST)BRC\n" +
      "5WV)157\n" +
      "XKM)NHS\n" +
      "T18)KN7\n" +
      "LPX)WDM\n" +
      "MTG)9KF\n" +
      "7ZX)ZNQ\n" +
      "LBK)483\n" +
      "RBC)SF5\n" +
      "ZYX)J82\n" +
      "HNZ)2BG\n" +
      "CMQ)F8T\n" +
      "SSQ)JMN\n" +
      "52P)TQN\n" +
      "7C8)WDW\n" +
      "754)QYF\n" +
      "MNW)1L4\n" +
      "THY)NG4\n" +
      "SCZ)5B4\n" +
      "DY3)7V8\n" +
      "3XX)M5S\n" +
      "G58)HJ3\n" +
      "SLL)6DZ\n" +
      "X83)PNS\n" +
      "7P3)XR9\n" +
      "FCX)LKP\n" +
      "JFL)PZW\n" +
      "KMT)F4C\n" +
      "4H7)KY4\n" +
      "4J3)6MV\n" +
      "GVN)L1G\n" +
      "HY4)WF3\n" +
      "Q8Z)ZST\n" +
      "1YK)81Q\n" +
      "NTS)PBB\n" +
      "BXW)XFD\n" +
      "SDL)M7G\n" +
      "9K2)CGY\n" +
      "14K)SXW\n" +
      "WBC)6YZ\n" +
      "CNF)MMF\n" +
      "J82)4LK\n" +
      "11N)4DZ\n" +
      "H18)N9C\n" +
      "9B8)DHW\n" +
      "JJX)MC7\n" +
      "ZZQ)R28\n" +
      "5B4)CQX\n" +
      "ZDF)46X\n" +
      "SJF)XSS\n" +
      "CBM)BS7\n" +
      "SSQ)CBB\n" +
      "25S)FQ3\n" +
      "ZSM)G4D\n" +
      "5FJ)W6Q\n" +
      "G4D)R4G\n" +
      "94V)TYQ\n" +
      "DYG)MSS\n" +
      "3JX)8P1\n" +
      "XGN)H32\n" +
      "K4W)GCH\n" +
      "SR1)QX5\n" +
      "QMD)CRR\n" +
      "3PX)LVM\n" +
      "GPR)Z96\n" +
      "87Q)L6K\n" +
      "Z2Y)P5J\n" +
      "5VW)FZL\n" +
      "5CW)TL3\n" +
      "H4Y)1ZY\n" +
      "Q8H)7HZ\n" +
      "F4K)HWM\n" +
      "Z49)5WM\n" +
      "DH1)YGR\n" +
      "XFR)7HY\n" +
      "J4L)JNL\n" +
      "2BZ)3LD\n" +
      "1D2)GNF\n" +
      "C8V)743\n" +
      "HRM)PDC\n" +
      "D9Z)PXH\n" +
      "NSC)LHB\n" +
      "9GQ)W27\n" +
      "GSJ)DVT\n" +
      "SVW)VB5\n" +
      "61M)BZS\n" +
      "HV2)KQ3\n" +
      "HXZ)CCM\n" +
      "DK4)8C8\n" +
      "7RJ)4SG\n" +
      "GJ1)KF3\n" +
      "C1Q)F5P\n" +
      "YBT)L2M\n" +
      "L9V)Q4K\n" +
      "TD4)H31\n" +
      "RN4)MT1\n" +
      "DNM)4YV\n" +
      "QFD)5YP\n" +
      "LCN)3Z1\n" +
      "JMX)C1L\n" +
      "Z81)B2X\n" +
      "NVJ)7BS\n" +
      "LWY)YCY\n" +
      "GJ9)CCY\n" +
      "5VB)QZ5\n" +
      "JFL)946\n" +
      "9LH)1WS\n" +
      "XWW)PLH\n" +
      "JDD)QXJ\n" +
      "G36)1T7\n" +
      "ZQ5)6G6\n" +
      "X9T)D9W\n" +
      "NCD)WXS\n" +
      "Q76)126\n" +
      "3WF)LC9\n" +
      "7CX)C9B\n" +
      "V5J)6CL\n" +
      "NL4)JWH\n" +
      "GRX)DWL\n" +
      "X4M)1MS\n" +
      "TVJ)LCS\n" +
      "B87)VWC\n" +
      "8KY)Y2P\n" +
      "KGM)QXZ\n" +
      "ZMG)VXJ\n" +
      "PS2)Z41\n" +
      "TNQ)RB2\n" +
      "RS8)GWJ\n" +
      "8CN)J2B\n" +
      "6KP)SSG\n" +
      "WYM)JXR\n" +
      "126)BWH\n" +
      "2RH)25T\n" +
      "TFG)4XQ\n" +
      "BD3)MWM\n" +
      "G97)XSP\n" +
      "D2J)CBM\n" +
      "MW1)3LZ\n" +
      "JJD)73T\n" +
      "8RX)WCM\n" +
      "C99)N5C\n" +
      "4TM)MYS\n" +
      "YK6)B7N\n" +
      "T65)7ST\n" +
      "7YK)1K3\n" +
      "6FF)6XQ\n" +
      "7Y2)9HD\n" +
      "8VS)FNM\n" +
      "QV6)9N4\n" +
      "59F)M14\n" +
      "YGZ)121\n" +
      "BH9)L6T\n" +
      "2BG)NPB\n" +
      "MSS)8D9\n" +
      "DSN)413\n" +
      "2F7)QLW\n" +
      "RX2)61S\n" +
      "5M4)4H7\n" +
      "VSJ)FMF\n" +
      "DD2)K9T\n" +
      "7TH)3DM\n" +
      "1QL)GT3\n" +
      "JQD)ZWS\n" +
      "QDV)S49\n" +
      "FC5)MNZ\n" +
      "KBL)LJY\n" +
      "DW5)NGJ\n" +
      "6C3)H8V\n" +
      "S4L)7G3\n" +
      "538)L4G\n" +
      "ZSR)HCW\n" +
      "VJG)ZKG\n" +
      "DZS)4N2\n" +
      "H96)555\n" +
      "2NV)956\n" +
      "HVB)NNP\n" +
      "JMF)HCD\n" +
      "9KS)8ZL\n" +
      "VHH)D7N\n" +
      "GZB)CHY\n" +
      "L6K)V4X\n" +
      "SWM)4PP\n" +
      "3FY)QMD\n" +
      "RT5)C9G\n" +
      "RJK)189\n" +
      "DNM)LD8\n" +
      "2VR)8LG\n" +
      "LP6)R96\n" +
      "TQN)5FJ\n" +
      "BSJ)N9B\n" +
      "DR7)G5M\n" +
      "749)CYX\n" +
      "KBL)NVJ\n" +
      "PJ6)Z6H\n" +
      "QBH)GB7\n" +
      "ZXP)C1Q\n" +
      "NWC)MM1\n" +
      "KCM)BBF\n" +
      "QP8)M7D\n" +
      "YLQ)G36\n" +
      "QRZ)2M7\n" +
      "Y8V)CM4\n" +
      "CQX)58W\n" +
      "B1Q)VSX\n" +
      "8C8)3R6\n" +
      "KF7)W8S\n" +
      "J7J)8XG\n" +
      "XQF)R2M\n" +
      "1D2)H8S\n" +
      "N4C)L2Z\n" +
      "BHV)GVT\n" +
      "FVY)3FB\n" +
      "5LS)M98\n" +
      "CQB)85D\n" +
      "B7L)WL1\n" +
      "816)S7X\n" +
      "H9D)L8R\n" +
      "1MC)YDC\n" +
      "6CJ)X6X\n" +
      "13Z)TL7\n" +
      "5RS)SQY\n" +
      "NRP)C5W\n" +
      "CMF)7VQ\n" +
      "BLZ)ZD5\n" +
      "YG3)TLS\n" +
      "KG1)N76\n" +
      "Y52)MVN\n" +
      "4F2)WW5\n" +
      "765)GS3\n" +
      "PS7)RYT\n" +
      "HVM)LM2\n" +
      "6XQ)T3K\n" +
      "C5W)996\n" +
      "9JY)DH4\n" +
      "C65)VGV\n" +
      "R95)Q74\n" +
      "JNZ)GH3\n" +
      "MMV)2RC\n" +
      "7Q1)85Q\n" +
      "PDC)XJ4\n" +
      "XHF)YQQ\n" +
      "TZ1)3TN\n" +
      "J36)JR3\n" +
      "SDT)68C\n" +
      "57F)GJ7\n" +
      "SVY)L9H\n" +
      "RML)12Y\n" +
      "698)2MZ\n" +
      "2R1)ZWN\n" +
      "RTK)KCV\n" +
      "Y8K)4XB\n" +
      "CT7)Q6Z\n" +
      "WBF)F1R\n" +
      "W6P)BZH\n" +
      "CYW)6KT\n" +
      "GFR)95Z\n" +
      "W28)GMM\n" +
      "XYY)L7N\n" +
      "8MF)4B4\n" +
      "6GH)8H3\n" +
      "NCL)74N\n" +
      "5WZ)FY1\n" +
      "2KC)Y8V\n" +
      "DQM)XVT\n" +
      "K92)XJF\n" +
      "QX5)8CD\n" +
      "RGW)97Q\n" +
      "HH8)F76\n" +
      "53L)DW5\n" +
      "LKP)X6Z\n" +
      "31X)863\n" +
      "LSM)JZM\n" +
      "QN8)44L\n" +
      "1WJ)JB2\n" +
      "C83)L1C\n" +
      "KFW)HLJ\n" +
      "MT1)GRX\n" +
      "P4S)GDK\n" +
      "FQ8)8YH\n" +
      "GXQ)7QB\n" +
      "GTB)ZMV\n" +
      "KVH)G56\n" +
      "4VS)CNF\n" +
      "PS7)632\n" +
      "7GG)6LS\n" +
      "SQY)398\n" +
      "Q28)3MR\n" +
      "1ZY)NSN\n" +
      "2GQ)Q4W\n" +
      "NX6)69Y\n" +
      "3CJ)789\n" +
      "174)F5N\n" +
      "GJK)MJT\n" +
      "LQS)HH3\n" +
      "JP8)BQ5\n" +
      "LSK)7NK\n" +
      "LLT)7KD\n" +
      "YRD)MQ6\n" +
      "H7P)317\n" +
      "JBC)M58\n" +
      "GJ7)XNK\n" +
      "ZVG)VTZ\n" +
      "34M)S3R\n" +
      "VSN)P7X\n" +
      "6JF)BPR\n" +
      "XYY)SLQ\n" +
      "JNL)WX7\n" +
      "TMJ)KF7\n" +
      "LP9)45K\n" +
      "HF6)P1V\n" +
      "12Y)SDL\n" +
      "GDP)3ZP\n" +
      "C7T)YN9\n" +
      "9ZH)BSJ\n" +
      "96T)7M9\n" +
      "FVN)5JS\n" +
      "G9P)8V3\n" +
      "MWK)PSP\n" +
      "TMJ)5JK\n" +
      "NHF)GCP\n" +
      "MQ6)74V\n" +
      "D35)VMF\n" +
      "P41)57L\n" +
      "L9H)WF2\n" +
      "4FF)T1H\n" +
      "F73)LH4\n" +
      "NSN)567\n" +
      "LCX)QSK\n" +
      "Q45)BP5\n" +
      "1XL)NVK\n" +
      "317)6X3\n" +
      "XNK)XGB\n" +
      "NL4)TXH\n" +
      "MWM)34K\n" +
      "NV5)6LZ\n" +
      "4PP)BB9\n" +
      "SLQ)XD2\n" +
      "Z5W)H1V\n" +
      "BBF)6V7\n" +
      "RPM)RQ6\n" +
      "3Z5)B6P\n" +
      "MTL)RLC\n" +
      "8FP)CDD\n" +
      "CHL)RWY\n" +
      "FY1)HQ5\n" +
      "DXD)JNZ\n" +
      "9XJ)WPQ\n" +
      "Q4K)P3F\n" +
      "B4M)Q1Q\n" +
      "8ZL)5CW\n" +
      "SXW)77W\n" +
      "2Z2)1DQ\n" +
      "7BS)25D\n" +
      "GN1)Z5D\n" +
      "X94)ZZQ\n" +
      "N9B)185\n" +
      "V6P)XV9\n" +
      "121)HYZ\n" +
      "W3X)JPJ\n" +
      "8BG)S6K\n" +
      "YVJ)QR5\n" +
      "K8W)QRN\n" +
      "XRK)1JQ\n" +
      "VB5)8CC\n" +
      "GX5)HS9\n" +
      "4CH)WBY\n" +
      "GS3)1Y5\n" +
      "YRW)XWX\n" +
      "LCS)GT8\n" +
      "DKX)14M\n" +
      "NL1)BHV\n" +
      "7VQ)SN8\n" +
      "R6S)QDD\n" +
      "Q4W)WT2\n" +
      "C9B)CSH\n" +
      "5KM)LCN\n" +
      "1TD)LCH\n" +
      "B4T)35C\n" +
      "M62)V2H\n" +
      "V4H)HN6\n" +
      "5KM)5WV\n" +
      "CZ2)WQB\n" +
      "VFD)WHM\n" +
      "9BX)X4H\n" +
      "FTQ)D3L\n" +
      "G6Q)QVX\n" +
      "5FG)8VH\n" +
      "89K)J6F\n" +
      "4XG)MST\n" +
      "HPB)JMY\n" +
      "PZW)Q6M\n" +
      "T8J)SDG\n" +
      "ZB4)635\n" +
      "2LH)8JV\n" +
      "157)N42\n" +
      "PDM)TX6\n" +
      "HCD)VSJ\n" +
      "NNP)99H\n" +
      "6GC)C8Z\n" +
      "NPB)4HS\n" +
      "S51)K92\n" +
      "5FD)SLY\n" +
      "GT8)PXC\n" +
      "45Q)8GJ\n" +
      "GNF)V9B\n" +
      "H8S)8VY\n" +
      "35Q)N1W\n" +
      "RC7)4XH\n" +
      "PJG)JDY\n" +
      "8SY)9JL\n" +
      "3T8)6NX\n" +
      "NG8)HBB\n" +
      "78Z)H56\n" +
      "H1X)GJ1\n" +
      "TRG)9JP\n" +
      "YML)KBL\n" +
      "CVG)179\n" +
      "YXG)R7S\n" +
      "4YV)N4F\n" +
      "SLV)SYS\n" +
      "XKM)ZSM\n" +
      "8X9)SXH\n" +
      "L27)NTT\n" +
      "N1K)GN1\n" +
      "MTG)264\n" +
      "X6M)WBP\n" +
      "SHZ)DH9\n" +
      "NJN)C5B\n" +
      "QXZ)SJF\n" +
      "GQ6)JM9\n" +
      "R66)9J3\n" +
      "BQ1)WH1\n" +
      "RQ6)LT6\n" +
      "XQS)3PX\n" +
      "5YP)7JD\n" +
      "WWX)5WZ\n" +
      "J3J)VV9\n" +
      "9B5)DNT\n" +
      "GTS)Y59\n" +
      "BXS)SYQ\n" +
      "9DN)GTW\n" +
      "XM7)C3M\n" +
      "S3K)KHZ\n" +
      "V2H)LQS\n" +
      "SFK)FHB\n" +
      "6GC)732\n" +
      "YN3)KQM\n" +
      "W4N)2TX\n" +
      "B87)XXZ\n" +
      "ZV1)4FD\n" +
      "SG3)YB8\n" +
      "ZBM)87Q\n" +
      "V33)JWT\n" +
      "JDY)8YQ\n" +
      "5JC)5Y7\n" +
      "896)1T8\n" +
      "QXJ)K2S\n" +
      "68C)4QL\n" +
      "ZWX)WQD\n" +
      "KKF)B64\n" +
      "2FT)8QL\n" +
      "3WM)CSR\n" +
      "PGH)GD9\n" +
      "R36)817\n" +
      "NGJ)MM2\n" +
      "2ML)QDV\n" +
      "H8V)1GZ\n" +
      "C9G)QSS\n" +
      "TYQ)95C\n" +
      "MXZ)PMQ\n" +
      "98V)RNS\n" +
      "PLJ)LW1\n" +
      "JPJ)527\n" +
      "H31)NVN\n" +
      "N1L)8KT\n" +
      "RQ2)97J\n" +
      "FGW)YV8\n" +
      "B92)5M8\n" +
      "B63)V3M\n" +
      "7HZ)VR4\n" +
      "4NF)PK6\n" +
      "W67)66M\n" +
      "B9H)Y15\n" +
      "FYQ)6S7\n" +
      "CGP)D96\n" +
      "FRP)NFK\n" +
      "B61)DNM\n" +
      "VP3)8WZ\n" +
      "NG4)P5K\n" +
      "B3J)J5T\n" +
      "DQZ)X6W\n" +
      "B7D)9CN\n" +
      "ZDZ)FXR\n" +
      "R7S)Q7J\n" +
      "CNZ)94J\n" +
      "LPJ)QYT\n" +
      "YBG)PTC\n" +
      "X6W)Y8K\n" +
      "F9C)CR3\n" +
      "VD9)X1R\n" +
      "JWH)CN9\n" +
      "S7L)8BG\n" +
      "WX7)DR7\n" +
      "M1J)1PN\n" +
      "LXC)G1M\n" +
      "CM8)HXJ\n" +
      "SL8)78T\n" +
      "PJ1)TMJ\n" +
      "PWY)D7G\n" +
      "V4F)KFW\n" +
      "4SG)VL2\n" +
      "8LS)1KR\n" +
      "YJ1)8J5\n" +
      "GFY)Q8H\n" +
      "XGR)S2V\n" +
      "JN1)W4N\n" +
      "5T5)7MD\n" +
      "1L5)RJK\n" +
      "85Q)KLK\n" +
      "68K)RGW\n" +
      "61S)TGR\n" +
      "Q56)B3G\n" +
      "LT6)FFL\n" +
      "8Q9)BD3\n" +
      "4WF)7BY\n" +
      "YDC)SFR\n" +
      "SSY)F11\n" +
      "XSP)4QM\n" +
      "W4T)J8Q\n" +
      "2N5)8CH\n" +
      "J6F)ZDZ\n" +
      "5WQ)Z7J\n" +
      "KWB)ZPY\n" +
      "4XH)2ZQ\n" +
      "KDC)L32\n" +
      "8LF)YNV\n" +
      "3GN)QTN\n" +
      "429)86C\n" +
      "B2X)FBR\n" +
      "3TN)BXW\n" +
      "CMY)HKM\n" +
      "2NX)HVB\n" +
      "QR5)MLR\n" +
      "99H)2LH\n" +
      "743)1MH\n" +
      "VGJ)S6H\n" +
      "NRJ)13Z\n" +
      "WX2)XM7\n" +
      "KSQ)KQ9\n" +
      "7JD)24M\n" +
      "VV9)5QP\n" +
      "BJZ)24X\n" +
      "7TG)Y9F\n" +
      "LJ6)XDR\n" +
      "JGY)6NG\n" +
      "4L3)6TD\n" +
      "3GR)3D2\n" +
      "88Y)GL3\n" +
      "6QZ)SSY\n" +
      "KD2)36J\n" +
      "TPV)GM7\n" +
      "2QR)CHL\n" +
      "XFN)5SG\n" +
      "B78)3XX\n" +
      "1MS)8PX\n" +
      "CH9)PY2\n" +
      "QDP)XRT\n" +
      "LN6)L4R\n" +
      "KQ9)148\n" +
      "M3D)VDM\n" +
      "P29)QRZ\n" +
      "3XM)JDK\n" +
      "L3S)7KL\n" +
      "HG3)213\n" +
      "TMN)GGW\n" +
      "4KK)WR3\n" +
      "113)BLS\n" +
      "95C)D35\n" +
      "BPD)PMJ\n" +
      "JWT)K1H\n" +
      "FMH)1B9\n" +
      "413)B7B\n" +
      "H32)MNM\n" +
      "J3N)J3J\n" +
      "GDK)YOU\n" +
      "8PQ)H96\n" +
      "QVX)PLQ\n" +
      "B2N)MGN\n" +
      "SF5)89K\n" +
      "NP7)SMY\n" +
      "SDG)PZ2\n" +
      "D3L)DTY\n" +
      "Z77)CPZ\n" +
      "B7M)5T5\n" +
      "D7G)PQX\n" +
      "NSC)KST\n" +
      "8T5)H89\n" +
      "PMS)1S2\n" +
      "8P1)9TF\n" +
      "J25)YKP\n" +
      "4CY)HNF\n" +
      "1K3)JXW\n" +
      "5RL)5MW\n" +
      "8FP)SLF\n" +
      "4FN)NTZ\n" +
      "ZSP)GTV\n" +
      "F8H)P7B\n" +
      "3L5)DBL\n" +
      "XRT)44D\n" +
      "MJP)QND\n" +
      "PM5)3QH\n" +
      "QMG)B78\n" +
      "BKZ)YVC\n" +
      "ZC5)NRP\n" +
      "4XB)QJV\n" +
      "7J5)JDD\n" +
      "7QS)VFT\n" +
      "CN9)784\n" +
      "QWH)129\n" +
      "P7X)VVC\n" +
      "ZWS)6WW\n" +
      "PMQ)RC7\n" +
      "BVM)JGY\n" +
      "F11)8T5\n" +
      "4XR)2LP\n" +
      "PQX)1SX\n" +
      "NV9)KD6\n" +
      "6WJ)2VX\n" +
      "NHS)YGK\n" +
      "81Q)Q9K\n" +
      "L2M)WWK\n" +
      "H5V)FKM\n" +
      "CY8)WYM\n" +
      "8RM)JTD\n" +
      "ZNB)HR4\n" +
      "CN9)6DV\n" +
      "52D)7MK\n" +
      "7MK)NG8\n" +
      "D3L)Z24\n" +
      "P2K)DNW\n" +
      "4H6)V89\n" +
      "LGZ)C4G\n" +
      "8LG)Z55\n" +
      "5B8)WDZ\n" +
      "Q74)WQF\n" +
      "F8T)L5D\n" +
      "DVT)4VM\n" +
      "H5V)XRC\n" +
      "DWL)82C\n" +
      "7Y7)CKM\n" +
      "4XK)YQD\n" +
      "2RC)6GH\n" +
      "FH9)ZJF\n" +
      "MJT)V9K\n" +
      "QSS)R7D\n" +
      "62H)K6S\n" +
      "ZFX)143\n" +
      "MGN)KZ5\n" +
      "8JR)54L\n" +
      "98Z)B5N\n" +
      "1GZ)SBB\n" +
      "8HF)FJ3\n" +
      "D6N)GFR\n" +
      "F76)BN7\n" +
      "DDR)K2W\n" +
      "2ZM)RZR\n" +
      "LCH)DXM\n" +
      "F5N)N1L\n" +
      "91M)H7P\n" +
      "QLW)BGN\n" +
      "744)YRD\n" +
      "GHZ)RKG\n" +
      "9HD)6L2\n" +
      "VMR)LJJ\n" +
      "42R)GTS\n" +
      "XFR)7P8\n" +
      "7YS)ZBM\n" +
      "HS9)QK9\n" +
      "FJL)BKZ\n" +
      "Q6Z)NCL\n" +
      "ZMV)FMH\n" +
      "9L2)4KT\n" +
      "LNL)V2L\n" +
      "NCX)2JF\n" +
      "HDL)F4Y\n" +
      "TXH)4XK\n" +
      "JPW)WX2\n" +
      "L4R)G6B\n" +
      "7V8)1R9\n" +
      "8RZ)ND1\n" +
      "ZNS)QPX\n" +
      "FNM)51Q\n" +
      "B1G)R66\n" +
      "38X)KH2\n" +
      "NPP)7DP\n" +
      "9J3)6C3\n" +
      "VLM)C83\n" +
      "KLK)YQM\n" +
      "HP3)BQ1\n" +
      "J32)VK7\n" +
      "PQX)GLK\n" +
      "FT1)C51\n" +
      "JBC)CGP\n" +
      "3GN)LSK\n" +
      "8HQ)9HT\n" +
      "B4P)XG2\n" +
      "3XX)7CC\n" +
      "B4K)SVY\n" +
      "LPY)LLT\n" +
      "BF3)YZ7\n" +
      "GHD)FL2\n" +
      "499)2L4\n" +
      "G2T)XKM\n" +
      "SXH)4KK\n" +
      "M5T)YSM\n" +
      "VX4)JXF\n" +
      "733)PVR\n" +
      "143)BJR\n" +
      "Y9T)FQ4\n" +
      "9KX)JXZ\n" +
      "NQF)3TQ\n" +
      "815)CKZ\n" +
      "1Z1)W4K\n" +
      "9TF)7ZY\n" +
      "NVR)QS3\n" +
      "MJC)1LB\n" +
      "RNP)3L3\n" +
      "5ZP)LVN\n" +
      "T3K)TFB\n" +
      "7WQ)72X\n" +
      "J7B)7CT\n" +
      "7CC)B63\n" +
      "5JS)BF5\n" +
      "9CJ)BD8\n" +
      "CXY)4VJ\n" +
      "FYZ)88H\n" +
      "C5Y)NM7\n" +
      "Z7S)T8J\n" +
      "TTB)9DN\n" +
      "J6Y)18Q\n" +
      "7J8)X94\n" +
      "YQ5)NCV\n" +
      "PTC)CQP\n" +
      "9KF)NL4\n" +
      "HQ5)GFM\n" +
      "8RY)LY8\n" +
      "T5B)14Y\n" +
      "F2F)3MH\n" +
      "L1C)Q17\n" +
      "MPC)VZG\n" +
      "JXT)KKF\n" +
      "WCM)HHL\n" +
      "GP7)GMJ\n" +
      "NCV)3L5\n" +
      "CKZ)1Z7\n" +
      "TL7)TPV\n" +
      "VG3)GZX\n" +
      "NVK)DY9\n" +
      "J1V)4VS\n" +
      "VHF)Z2Y\n" +
      "LW1)B1Q\n" +
      "P1J)W1D\n" +
      "JST)32Z\n" +
      "4MD)9L2\n" +
      "VGL)N7X\n" +
      "JPB)C5V\n" +
      "6P9)62H\n" +
      "LJC)DQM\n" +
      "R88)KBJ\n" +
      "N9V)LWY\n" +
      "RV1)VMR\n" +
      "4FD)1R7\n" +
      "ZYM)3F3\n" +
      "LKK)91M\n" +
      "PLH)QV6\n" +
      "2CB)YN3\n" +
      "24M)F1B\n" +
      "14Y)MCG\n" +
      "749)SDT\n" +
      "1MG)9JS\n" +
      "BWH)JWP\n" +
      "TSC)HTJ\n" +
      "Y73)SFK\n" +
      "F4C)8QZ\n" +
      "HB1)NJL\n" +
      "6VK)574\n" +
      "6DZ)SSQ\n" +
      "JZZ)B9Q\n" +
      "7YK)LQ5\n" +
      "M3Q)8K8\n" +
      "9RH)78Z\n" +
      "MVN)TBY\n" +
      "LVJ)YML\n" +
      "TF1)JWS\n" +
      "Q4R)7GG\n" +
      "8YB)1T4\n" +
      "NB6)TNN\n" +
      "GL3)4FN\n" +
      "NGP)M27\n" +
      "RBD)2MS\n" +
      "9FT)NRJ\n" +
      "MYS)SQB\n" +
      "LG7)8LS\n" +
      "XMJ)8SD\n" +
      "S6K)XKL\n" +
      "W6Q)49Z\n" +
      "3L3)3B4\n" +
      "2YF)N7B\n" +
      "9WC)JFL\n" +
      "8PX)DJJ\n" +
      "3NZ)4J3\n" +
      "3BF)L27\n" +
      "2ZR)6RY\n" +
      "FFZ)ZMF\n" +
      "WBY)RXQ\n" +
      "2TP)FQX\n" +
      "9VT)MJC\n" +
      "RQ2)K9V\n" +
      "94J)BHS\n" +
      "PX2)HNT\n" +
      "7VQ)TW6\n" +
      "M58)F1G\n" +
      "8VY)S8T\n" +
      "LSV)88D\n" +
      "KCV)VHH\n" +
      "WQN)2NF\n" +
      "LZZ)VCT\n" +
      "LR9)L9G\n" +
      "6JB)S3K\n" +
      "MBJ)VS6\n" +
      "VXJ)CY6\n" +
      "TY3)MNT\n" +
      "2F7)NV5\n" +
      "ZN4)ZL1\n" +
      "B7N)HZH\n" +
      "8BK)78Q\n" +
      "HHL)F3M\n" +
      "ZWH)MPH\n" +
      "W4G)CH8\n" +
      "CT7)B4T\n" +
      "NNK)5KM\n" +
      "W82)Q6Y\n" +
      "WZC)4D9\n" +
      "5DC)WN2\n" +
      "2CN)HB1\n" +
      "ZF3)VY9\n" +
      "2JS)MYC\n" +
      "P5J)LPJ\n" +
      "WCG)5CY\n" +
      "KFN)94C\n" +
      "754)RTK\n" +
      "CW8)KSR\n" +
      "K8M)V3Y\n" +
      "DQV)MGG\n" +
      "RC7)8M2\n" +
      "MGG)FFZ\n" +
      "GWT)FJL\n" +
      "6RY)CXY\n" +
      "KBM)G4C\n" +
      "Z59)HXX\n" +
      "74V)T5H\n" +
      "K3B)SVW\n" +
      "WWK)2BK\n" +
      "M98)JZZ\n" +
      "YVC)TXJ\n" +
      "RWY)46R\n" +
      "7S6)YK6\n" +
      "B64)YBT\n" +
      "2C7)FCX\n" +
      "VWL)VD9\n" +
      "RML)FC6\n" +
      "KF5)WBF\n" +
      "LM5)XVD\n" +
      "4VM)H53\n" +
      "4QL)1S9\n" +
      "5MM)FPR\n" +
      "ZJF)GQH\n" +
      "9HT)2BZ\n" +
      "D9W)8B9\n" +
      "CCC)PYF\n" +
      "78H)F8H\n" +
      "YM1)B6F\n" +
      "85D)Z69\n" +
      "XRC)D6N\n" +
      "KZD)QFD\n" +
      "HXJ)XQD\n" +
      "X6Z)K4W\n" +
      "HCL)FTQ\n" +
      "XVT)FGW\n" +
      "7QB)1SN\n" +
      "GMS)RGY\n" +
      "X53)RC8\n" +
      "YQ7)2TP\n" +
      "BJY)3FL\n" +
      "H5D)Q1C\n" +
      "X5W)F2F\n" +
      "SCV)RX2\n" +
      "QW7)HNZ\n" +
      "L23)3JX\n" +
      "5KX)PMS\n" +
      "BP5)WPY\n" +
      "KH2)3ZX\n" +
      "ZST)1JY\n" +
      "H9G)V6S\n" +
      "DXC)MJP\n" +
      "6PB)V23\n" +
      "NYC)CMF\n" +
      "8ZS)1F4\n" +
      "ZRQ)FH4\n" +
      "KL1)JR6\n" +
      "JMY)J2X\n" +
      "DXC)8G9\n" +
      "SB3)89S\n" +
      "1YT)2L6\n" +
      "LH4)99L\n" +
      "N4F)C1C\n" +
      "K9W)NCX\n" +
      "5MM)2F7\n" +
      "1T4)5H6\n" +
      "DNW)4B7\n" +
      "3L6)S53\n" +
      "YV8)1Y9\n" +
      "85F)6CJ\n" +
      "RLZ)9JY\n" +
      "1F6)64C\n" +
      "T75)GQ3\n" +
      "B5R)ZYX\n" +
      "Q1B)L9V\n" +
      "WHM)PJ6\n" +
      "P7B)9GQ\n" +
      "XD2)Z4Y\n" +
      "347)499\n" +
      "TK5)GZ4\n" +
      "8NW)82H\n" +
      "M7R)S4L\n" +
      "B11)3L6\n" +
      "RPZ)SLL\n" +
      "77W)XSG\n" +
      "CZ2)8NW\n" +
      "3FY)GX8\n" +
      "2ML)NL1\n" +
      "6BV)H5D\n" +
      "8GH)PM9\n" +
      "XVY)JNJ\n" +
      "93T)W9D\n" +
      "QJ7)11N\n" +
      "SYX)GP7\n" +
      "TXH)823\n" +
      "PSS)W82\n" +
      "67H)1F6\n" +
      "J7P)HWY\n" +
      "W1D)NB6\n" +
      "6J2)YJ1\n" +
      "J25)DTQ\n" +
      "HWM)JPW\n" +
      "4VV)ZX7\n" +
      "CCY)X6M\n" +
      "S7X)FK6\n" +
      "F8R)NN6\n" +
      "3G1)YVJ\n" +
      "FYZ)WCG\n" +
      "SLF)LHX\n" +
      "941)Y94\n" +
      "2NF)HY4\n" +
      "4XQ)L95\n" +
      "F55)QBJ\n" +
      "GJN)9CJ\n" +
      "26S)B7L\n" +
      "S2N)4V3\n" +
      "FMH)3YR\n" +
      "TQC)RSR\n" +
      "1NM)1VY\n" +
      "CK7)LQH\n" +
      "BN7)2WF\n" +
      "4B4)Y73\n" +
      "QSK)7Y7\n" +
      "J7V)8R4\n" +
      "P3W)X6V\n" +
      "LSR)2Z7\n" +
      "62H)6WJ\n" +
      "7G3)3WF\n" +
      "HH3)V77\n" +
      "88H)RB1\n" +
      "PVR)CMY\n" +
      "MST)R6S\n" +
      "VB5)5TC\n" +
      "V23)VX4\n" +
      "BGN)6TZ\n" +
      "31X)MD1\n" +
      "JY4)MXP\n" +
      "1JY)RQ5\n" +
      "R1H)JJD\n" +
      "4QL)H9L\n" +
      "84C)J7B\n" +
      "1L4)XCV\n" +
      "KF3)ZWX\n" +
      "MQH)D9Z\n" +
      "G56)BN6\n" +
      "555)P15\n" +
      "P6F)H4L\n" +
      "GWJ)8Q7\n" +
      "MCG)42J\n" +
      "LJY)7YS\n" +
      "HXW)1WP\n" +
      "FK6)68G\n" +
      "T2T)K4B\n" +
      "ZN5)P2K\n" +
      "7QB)C65\n" +
      "J65)RT5\n" +
      "KNZ)P51\n" +
      "HYZ)45Q\n" +
      "239)53F\n" +
      "CYW)YQ5\n" +
      "9DZ)1Z1\n" +
      "185)ND9\n" +
      "MZM)1M5\n" +
      "WXS)JHN\n" +
      "TN1)F7V\n" +
      "3GL)M1J\n" +
      "GXQ)GFY\n" +
      "C5V)LGL\n" +
      "XJ4)JQD\n" +
      "FQ3)X53\n" +
      "6TV)JFN\n" +
      "Y9F)QM7\n" +
      "T1H)NYC\n" +
      "VWC)CMQ\n" +
      "MC7)J63\n" +
      "GTW)6GC\n" +
      "8WZ)Q1B\n" +
      "D96)7J8\n" +
      "KF7)59X\n" +
      "KS9)LG7\n" +
      "9J3)ZSD\n" +
      "G4C)PHX\n" +
      "BRC)D5Z\n" +
      "8G9)QDX\n" +
      "FV4)2PZ\n" +
      "F58)R8P\n" +
      "QW2)FYZ\n" +
      "VT2)Y9T\n" +
      "6VB)BJY\n" +
      "ZZ1)X9Q\n" +
      "K5L)ZDQ\n" +
      "148)WBC\n" +
      "1KR)TZD\n" +
      "WW4)FPV\n" +
      "ND1)W3Y\n" +
      "2NV)CQR\n" +
      "C8W)T75\n" +
      "XVD)RQ2\n" +
      "L7F)1L5\n" +
      "TGR)6GD\n" +
      "S3R)WVH\n" +
      "NHT)8JR\n" +
      "J65)TP4\n" +
      "F3M)GX5\n" +
      "789)XSC\n" +
      "K3Z)754\n" +
      "GFB)83W\n" +
      "LHB)9B5\n" +
      "HC2)F86\n" +
      "LNZ)L2G\n" +
      "FQ3)6CS\n" +
      "BY9)96T\n" +
      "C3X)G62\n" +
      "KP5)MR1\n" +
      "PY9)M5T\n" +
      "RB1)5J9\n" +
      "KRP)6MD\n" +
      "V6C)MCS\n" +
      "B3T)YG3\n" +
      "MQR)6BV\n" +
      "BF5)5VW\n" +
      "DJJ)CX9\n" +
      "GP4)7DN\n" +
      "XVD)Q3Y\n" +
      "RCW)JXT\n" +
      "SYQ)8JP\n" +
      "DZ4)G97\n" +
      "BV4)W4C\n" +
      "R9D)HJW\n" +
      "LJJ)HRM\n" +
      "K9W)CBF\n" +
      "JNJ)B92\n" +
      "VFT)LM9\n" +
      "SQP)ZDF\n" +
      "S2V)2QR\n" +
      "6XH)G2T\n" +
      "1VY)F6X\n" +
      "QG2)8DW\n" +
      "42J)98V\n" +
      "G3T)9TC\n" +
      "8KB)245\n" +
      "S4K)Y7R\n" +
      "FNS)LM5\n" +
      "SKS)FGN\n" +
      "5H6)9S5\n" +
      "LW4)HGD\n" +
      "FHL)SBP\n" +
      "9V4)B42\n" +
      "YCG)TF1\n" +
      "5TN)12C\n" +
      "QDD)TP1\n" +
      "BP8)4VV\n" +
      "5QP)B4P\n" +
      "N2S)WLV\n" +
      "L5D)XXP\n" +
      "2SF)TRG\n" +
      "MW8)995\n" +
      "XCV)BJZ\n" +
      "F2S)FNS\n" +
      "Z8N)43L\n" +
      "K9T)TSX\n" +
      "NM7)7J5\n" +
      "97Q)X5W\n" +
      "R94)8SY\n" +
      "ZDQ)NPP\n" +
      "85V)B99\n" +
      "6QF)W9G\n" +
      "GB7)H9G\n" +
      "VLN)ZNS\n" +
      "4XR)D2J\n" +
      "8D9)SZ6\n" +
      "2ZJ)1D4\n" +
      "F53)TTB\n" +
      "ZT1)9VW\n" +
      "41J)W67\n" +
      "CBF)HPB\n" +
      "RKG)42R\n" +
      "62K)57F\n" +
      "7ZQ)R95\n" +
      "6G6)W6P\n" +
      "R7W)H5X\n" +
      "QDJ)RQP\n" +
      "TNN)WRX\n" +
      "7DP)HVM\n" +
      "3R6)S7L\n" +
      "7P8)8B2\n" +
      "JSQ)JPG\n" +
      "9BC)94V\n" +
      "M5B)GXQ\n" +
      "2Z7)3GN\n" +
      "C64)FLR\n" +
      "P56)YLZ\n" +
      "4HS)DZS\n" +
      "8GK)QFQ\n" +
      "9BQ)F1F\n" +
      "V2L)437\n" +
      "SQB)GPR\n" +
      "D5B)XVV\n" +
      "QF5)HSP\n" +
      "5MW)J9T\n" +
      "W4K)6J2\n" +
      "5TC)XGR\n" +
      "XLL)ZFX\n" +
      "Q56)LN6\n" +
      "JR3)ZP8\n" +
      "JR6)5M4\n" +
      "3HB)23L\n" +
      "YW5)4CY\n" +
      "NPP)B1B\n" +
      "6NX)V6C\n" +
      "1MP)VQZ\n" +
      "2MZ)7ZQ\n" +
      "8JR)1MC\n" +
      "LVN)58K\n" +
      "61K)LZT\n" +
      "5FL)LZZ\n" +
      "6B8)64W\n" +
      "G1M)B1G\n" +
      "WM3)T1T\n" +
      "V89)N9V\n" +
      "QS3)3FN\n" +
      "D5Z)NQT\n" +
      "ZM1)5J7\n" +
      "D7N)8XB\n" +
      "XSS)Y37\n" +
      "2Q3)PWY\n" +
      "Y94)MW8\n" +
      "GBY)RGP\n" +
      "XTN)G6Q\n" +
      "JXR)GMS\n" +
      "8JP)MXZ\n" +
      "F86)DTZ\n" +
      "RCH)3VC\n" +
      "524)14K\n" +
      "G6Y)HV2\n" +
      "RZY)BLZ\n" +
      "N7X)8GK\n" +
      "7QV)35Q\n" +
      "2PZ)55N\n" +
      "318)BNR\n" +
      "ND9)7QV\n" +
      "HR2)FP6\n" +
      "RGP)9K3\n" +
      "8PS)SB3\n" +
      "LM2)L48\n" +
      "R15)NTS\n" +
      "G7Y)CQB\n" +
      "J6F)YQ7\n" +
      "VTZ)YNX\n" +
      "VG3)C8W\n" +
      "XDL)3NN\n" +
      "FJ1)FK1\n" +
      "MM1)4MD\n" +
      "96S)NCY\n" +
      "T5H)3FY\n" +
      "3LD)1PH\n" +
      "989)X3M\n" +
      "Q1C)SAN\n" +
      "YB8)XDN\n" +
      "FK1)LJ6\n" +
      "ZP5)J48\n" +
      "RNP)V33\n" +
      "W5F)Q8N\n" +
      "22G)DQZ\n" +
      "1G8)C3X\n" +
      "GCH)46Q\n" +
      "G3X)ZT1\n" +
      "ZD4)GTN\n" +
      "Z21)5RS\n" +
      "YV9)4GF\n" +
      "TLS)NQ3\n" +
      "X3M)8LF\n" +
      "9J1)SDF\n" +
      "HKM)KFN\n" +
      "JPG)DXC\n" +
      "C5B)8CN\n" +
      "YNX)P3W\n" +
      "QYF)GHZ\n" +
      "GGW)FV4\n" +
      "TTR)5JX\n" +
      "HWY)2SF\n" +
      "MLR)JZC\n" +
      "9ZD)JVW\n" +
      "2ZK)LGZ\n" +
      "GQH)NPC\n" +
      "76W)H5V\n" +
      "2Q7)B7D\n" +
      "264)M3D\n" +
      "YKP)53L\n" +
      "CM4)PD8\n" +
      "GX8)52P\n" +
      "3YR)DR5\n" +
      "ZSD)P2X\n" +
      "T9T)KLW\n" +
      "JM9)9D2\n" +
      "JRR)8RM\n" +
      "9PV)G9X\n" +
      "VHG)5B8\n" +
      "8JP)752\n" +
      "Q89)F2M\n" +
      "TR9)GBY\n" +
      "GMJ)XVN\n" +
      "K6V)7P3\n" +
      "QRN)ZNB\n" +
      "7M9)P6F\n" +
      "NTZ)KJP\n" +
      "LPY)KT2\n" +
      "C5Y)X4Z\n" +
      "Z27)34M\n" +
      "TSX)3T8\n" +
      "WPY)CH9\n" +
      "LZT)QD5\n" +
      "W1T)GDP\n" +
      "CCC)XGV\n" +
      "XDN)CKN\n" +
      "9JY)4TM\n" +
      "L2G)6KP\n" +
      "F25)6TV\n" +
      "23L)JMX\n" +
      "4KC)2ZK\n" +
      "3F3)XNG\n" +
      "92P)SHT\n" +
      "L1G)3YT\n" +
      "58W)M7R\n" +
      "9F2)459\n" +
      "S8J)8ZS\n" +
      "GSB)G7J\n" +
      "XVN)62K\n" +
      "899)PZH\n" +
      "1PH)GJD\n" +
      "YKP)SR1\n" +
      "JV9)YYN\n" +
      "3R3)PSS\n" +
      "YRW)KP3\n" +
      "HXX)8SQ\n" +
      "WDW)9B8\n" +
      "HCW)TSC\n" +
      "KP3)YKT\n" +
      "9XX)BFY\n" +
      "4VJ)XRK\n" +
      "FJS)LSM\n" +
      "N7L)Z7S\n" +
      "P15)P1J\n" +
      "GF1)RML\n" +
      "V9B)RM9\n" +
      "CY6)QW7\n" +
      "Z4L)QGH\n" +
      "7HY)DZ4\n" +
      "CYJ)9WN\n" +
      "YLZ)JSQ\n" +
      "2RY)VK8\n" +
      "3MH)7S6\n" +
      "86F)S51\n" +
      "YZ7)KG1\n" +
      "3F8)9KR\n" +
      "8RP)Z8N\n" +
      "1S9)LVJ\n" +
      "F5P)J6X\n" +
      "W6C)ZY5\n" +
      "TX6)ZRQ\n" +
      "B3Z)SL8\n" +
      "9B3)FQ8\n" +
      "Y5T)DFN\n" +
      "FC6)7TG\n" +
      "QK9)8RY\n" +
      "L2Z)B9H\n" +
      "R8P)G7Y\n" +
      "RQP)VFD\n" +
      "ZDZ)G6Y\n" +
      "KL8)7MT\n" +
      "72X)KD2\n" +
      "87V)V71\n" +
      "8SD)RPM\n" +
      "CCM)BVX\n" +
      "WQD)H7J\n" +
      "3YT)G3T\n" +
      "BPR)ZYM\n" +
      "CPZ)8PQ\n" +
      "BLZ)PCV\n" +
      "FBM)4WF\n" +
      "W8S)GJ9\n" +
      "HH8)9VT\n" +
      "GTV)FYQ\n" +
      "DH4)R8T\n" +
      "NKM)HF6\n" +
      "9K3)DKX\n" +
      "FBR)347\n" +
      "CRR)2NV\n" +
      "VK7)ML7\n" +
      "DBY)V3L\n" +
      "6B8)176\n" +
      "WMC)RG1\n" +
      "6XH)P56\n" +
      "QJY)6VK\n" +
      "FH4)FHL\n" +
      "5SG)LCX\n" +
      "MNZ)38X\n" +
      "VH2)113\n" +
      "51Q)PG6\n" +
      "K18)PSV\n" +
      "5JX)K8M\n" +
      "35C)NVR\n" +
      "Z5H)941\n" +
      "CLF)BPD\n" +
      "Z2Y)QXV\n" +
      "WKV)QF5\n" +
      "44L)S89\n" +
      "5QP)HH8\n" +
      "W1D)M62\n" +
      "NQT)12G\n" +
      "DXM)3Q1\n" +
      "X9Q)FBM\n" +
      "WBP)Y61\n" +
      "XJF)KS9\n" +
      "LQ5)793\n" +
      "8LV)N4C\n" +
      "44L)N3G\n" +
      "QPX)5FG\n" +
      "VZG)4CD\n" +
      "QD5)8X9\n" +
      "KQ3)DZL\n" +
      "WH1)LP9\n" +
      "793)VLM\n" +
      "78H)8RX\n" +
      "WYH)K9W\n" +
      "MNT)73Y\n" +
      "QYN)VTS\n" +
      "PD8)VG3\n" +
      "JZC)KVH\n" +
      "NRZ)8HF\n" +
      "H1Z)7YK\n" +
      "7MD)F53\n" +
      "WP8)PDM\n" +
      "JXF)HC2\n" +
      "5VW)B77\n" +
      "X6V)R36\n" +
      "4DZ)W53\n" +
      "8YQ)5DC\n" +
      "FBH)QP8\n" +
      "LG9)XPB\n" +
      "398)T88\n" +
      "QTN)JL2\n" +
      "N76)17X\n" +
      "NB1)7ZX\n" +
      "73T)4RG\n" +
      "J7P)XQF\n" +
      "8DS)3G7\n" +
      "MYC)NKM\n" +
      "YCK)F2S\n" +
      "64W)MWN\n" +
      "FMF)GP4\n" +
      "2GQ)91P\n" +
      "SLY)JST\n" +
      "F1F)K3Z\n" +
      "MD1)VSN\n" +
      "74N)NSC\n" +
      "HLJ)S8J\n" +
      "57L)LNL\n" +
      "GZ4)BC7\n" +
      "DR5)1YK\n" +
      "1Y5)R9D\n" +
      "Z5T)9B3\n" +
      "Y8V)5MM\n" +
      "HZH)K6V\n" +
      "SMY)52C\n" +
      "8BG)P28\n" +
      "QLQ)P4S\n" +
      "6NB)8CR\n" +
      "P5V)SKS\n" +
      "N42)8GN\n" +
      "5JK)4F2\n" +
      "BXQ)T9T\n" +
      "ZL1)WKD\n" +
      "KDC)7XM\n" +
      "721)PNV\n" +
      "W4G)J65\n" +
      "Z7J)G58\n" +
      "H7J)9DZ\n" +
      "4QM)67H\n" +
      "2LP)2ZJ\n" +
      "ND9)NQF\n" +
      "YKL)QG2\n" +
      "L7N)KWB\n" +
      "Z5D)1VV\n" +
      "LWF)HXZ\n" +
      "HRF)BH9\n" +
      "82H)FJ1\n" +
      "LPX)P33\n" +
      "8GJ)XPM\n" +
      "6BJ)HP6\n" +
      "W53)58H\n" +
      "SWQ)QJ8\n" +
      "XFF)LS6\n" +
      "189)CW8\n" +
      "BNR)Z8T\n" +
      "R8T)NLQ\n" +
      "R48)M1M\n" +
      "Y37)PGH\n" +
      "8CD)WYH\n" +
      "DHW)3BF\n" +
      "PXH)3TK\n" +
      "JFN)XYY\n" +
      "C9W)VP3\n" +
      "H4L)QJ7\n" +
      "8CC)NRK\n" +
      "P95)524\n" +
      "WQH)SXR\n" +
      "9DZ)8KY\n" +
      "3DM)7LD\n" +
      "8VY)6B8\n" +
      "CKM)H1Z\n" +
      "3VC)GDZ\n" +
      "LC9)HDL\n" +
      "N7B)165\n" +
      "95Z)ZZ1\n" +
      "567)T95\n" +
      "HPB)HG3\n" +
      "7XM)X2G\n" +
      "F3M)D3C\n" +
      "KY4)Z21\n" +
      "WT2)VHK\n" +
      "TP4)THY\n" +
      "LHX)F9T\n" +
      "QJY)78H\n" +
      "54L)WDD\n" +
      "7MT)8KB\n" +
      "GT3)V4H\n" +
      "D5G)3R3\n" +
      "79L)V4F\n" +
      "1PN)PVH\n" +
      "H96)9WJ\n" +
      "JWS)PJ3\n" +
      "7DN)RN4\n" +
      "KMT)2ZR\n" +
      "C4V)B4K\n" +
      "DY9)6QZ\n" +
      "53S)7RM\n" +
      "PZH)GFW\n" +
      "GWT)HBP\n" +
      "3D2)7QS\n" +
      "732)CHW\n" +
      "MYG)YSQ\n" +
      "WF3)CNZ\n" +
      "BD3)FT1\n" +
      "GLK)WCL\n" +
      "BC7)2KD\n" +
      "BFQ)9CK\n" +
      "NW3)GJN\n" +
      "35Q)Z81\n" +
      "32Z)6B2\n" +
      "C8W)9BT\n" +
      "H9D)G5F\n" +
      "B42)R7W\n" +
      "B19)MNK\n" +
      "RYT)J1V\n" +
      "B97)8LK\n" +
      "79J)XDL\n" +
      "GZX)GHD\n" +
      "QYN)Z5W\n" +
      "Y59)6NB\n" +
      "7TG)MW1\n" +
      "D45)RZY\n" +
      "GTW)ZV1\n" +
      "W48)XYN\n" +
      "3PZ)D82\n" +
      "GFM)8HQ\n" +
      "FKM)R3Q\n" +
      "B4H)41J\n" +
      "TGW)XFF\n" +
      "Z8T)GDF\n" +
      "1LB)YX4\n" +
      "C95)5JC\n" +
      "179)NX3\n" +
      "47G)ZXP\n" +
      "34K)2CB\n" +
      "Q4R)RNV\n" +
      "1B9)LR9\n" +
      "F1R)QWH\n" +
      "574)KL1\n" +
      "53F)J7P\n" +
      "VR4)YCB\n" +
      "C1L)6QF\n" +
      "LS6)GF1\n" +
      "NLQ)266\n" +
      "ZY5)NWC\n" +
      "64C)9XX\n" +
      "XDR)XKP\n" +
      "7CT)3LH\n" +
      "Q9K)Z5T\n" +
      "CDD)DMX\n" +
      "H5X)NNZ\n" +
      "Z55)M3C\n" +
      "YYN)C99\n" +
      "FCJ)M54\n" +
      "JN1)H1X\n" +
      "1MH)698\n" +
      "9ZH)YCK\n" +
      "FDR)46M\n" +
      "C3M)LW4\n" +
      "DRD)MZM\n" +
      "HBP)LNZ\n" +
      "79X)Q5G\n" +
      "QND)3XM\n" +
      "98C)SWM\n" +
      "DTQ)RL6\n" +
      "WQB)FH9\n" +
      "58K)L4K\n" +
      "NH9)V3R\n" +
      "PLQ)BV4\n" +
      "73Y)61K\n" +
      "CHY)5ZP\n" +
      "SBP)8BB\n" +
      "RB2)BBB\n" +
      "91P)WMC\n" +
      "XFD)5VB\n" +
      "BHS)MQH\n" +
      "MR1)NHF\n" +
      "8SQ)59T\n" +
      "8B2)7Y2\n" +
      "6FG)FRP\n" +
      "XFC)XVY\n" +
      "BP7)FBH\n" +
      "K5L)WY1\n" +
      "XVV)PM5\n" +
      "FD7)LPY\n" +
      "DFN)XF3\n" +
      "XXZ)JZ6\n" +
      "GVT)J32\n" +
      "GCP)MBJ\n" +
      "25D)8RZ\n" +
      "WBJ)JJX\n" +
      "5J9)Z5H\n" +
      "8V3)HCL\n" +
      "PZ2)1LQ\n" +
      "NQ3)P8C\n" +
      "J5T)6F6\n" +
      "LP6)9J1\n" +
      "XGR)B87\n" +
      "MK7)TFG\n" +
      "6TZ)DXD\n" +
      "KR4)CK7\n" +
      "8JV)L3R\n" +
      "P5M)174\n" +
      "946)HP3\n" +
      "1VV)XQS\n" +
      "47G)VRX\n" +
      "MYJ)B11\n" +
      "9JL)5TN\n" +
      "B98)KFZ\n" +
      "W82)RS8\n" +
      "NVJ)7XH\n" +
      "KP3)B5R\n" +
      "JDK)XLL\n" +
      "GWJ)J5G";
}
